default_platform :ios

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Fraakost") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(scheme: "Fraakost") # Build your app - more options available
    deliver(force: true)
  end
end
